-- Clear existing questions and insert new accounting questions
DELETE FROM public.questions;

-- Insert complete accounting questionnaire (49 questions)
INSERT INTO public.questions (question_text, option_1, option_2, option_3, option_4, correct_option) VALUES
('¿Qué es el Balance General?', 'Documentos legales para contratos', 'Informes sobre el patrimonio y su evolución', 'Resúmenes de ventas diarias', 'Declaraciones fiscales', 2),
('¿Cuál de las siguientes es una cualidad de la información contable?', 'Pertinencia', 'Irrelevancia', 'Complejidad', 'Ambigüedad', 1),
('El balance general también es conocido como:', 'Estado de Resultados', 'Estado de Flujo de Efectivo', 'Estado de Situación Patrimonial', 'Estado de Capital', 3),
('¿Qué informa el Estado de Resultados?', 'La evolución del patrimonio neto', 'Resultados de la gestión de la empresa', 'Cuentas por cobrar', 'Activos fijos', 2),
('El objetivo del balance es:', 'Mostrar únicamente activos', 'Brindar información sobre activos, pasivos y patrimonio', 'Calcular impuestos', 'Determinar sueldos', 2),
('¿Cuál es un libro contable principal?', 'Libro de Asistencia', 'Libro Diario', 'Libro de Inventario Físico', 'Libro de Compras', 2),
('El libro mayor se utiliza para:', 'Resumir y clasificar información del Diario', 'Registrar ventas diarias', 'Calcular impuestos', 'Pagar salarios', 1),
('El comprobante que respalda una venta es:', 'Pagaré', 'Recibo', 'Factura', 'Boleta de Depósito', 3),
('Un cheque diferido es aquel que:', 'Se cobra inmediatamente', 'Se cobra en fecha futura', 'No se puede cobrar', 'Es nominativo', 2),
('La planilla de aportes sirve para:', 'Declarar impuestos a la renta', 'Pagar salarios', 'Presentar aportes al IPS', 'Hacer inventarios', 3),
('¿Qué es el principio de comparabilidad?', 'Permite analizar información de distintos periodos', 'Obliga a usar las mismas cuentas', 'Evita errores contables', 'Elimina duplicaciones', 1),
('¿Qué son las cuentas regularizadoras?', 'Cuentas de ajuste que reducen valores', 'Cuentas de ventas', 'Cuentas bancarias', 'Cuentas de reservas', 1),
('Un balance de liquidación definitiva se realiza:', 'Al inicio del ejercicio', 'Al cierre habitual', 'Al final de la empresa', 'En fechas intermedias', 3),
('El estado de evolución del patrimonio neto muestra:', 'Activos corrientes', 'Variación del capital, reservas y resultados', 'Pasivos financieros', 'Gastos de administración', 2),
('¿Qué documento detalla el pago de salarios?', 'Planilla de aportes', 'Liquidación de salario', 'Factura', 'Pagaré', 2),
('Un pagaré al portador es:', 'No transferible', 'Transferible por endoso', 'Sin beneficiario designado', 'Solo bancario', 3),
('El cheque cruzado se cobra:', 'En ventanilla libre', 'Solo en un banco', 'Por cualquier persona', 'En efectivo inmediato', 2),
('¿Qué son los gastos pagados por anticipado?', 'Pagos futuros', 'Pagos realizados antes de su vencimiento', 'Pagos vencidos', 'Pagos condicionales', 2),
('El flujo de efectivo informa sobre:', 'Ingresos y egresos de dinero', 'Inventarios', 'Cuentas por cobrar', 'Activos fijos', 1),
('La reserva legal pertenece a:', 'Activos', 'Pasivos', 'Patrimonio neto', 'Gastos', 3),
('¿Qué son los bienes de cambio?', 'Bienes para uso interno', 'Bienes destinados a la venta', 'Bienes intangibles', 'Bienes en construcción', 2),
('El libro inventario registra:', 'Solo ventas', 'Activos, Pasivos y Patrimonio Neto iniciales', 'Movimientos bancarios', 'Planillas salariales', 2),
('La clasificación corriente y no corriente depende de:', 'Liquidez y tiempo', 'Tipo de activo', 'Cantidad de empleados', 'Ubicación geográfica', 1),
('El Estado de Resultados incluye:', 'Ingresos y gastos', 'Solo activos', 'Reservas y capital', 'Aportes patronales', 1),
('Los descuentos en ventas aparecen en:', 'Pasivo', 'Estado de Resultados', 'Balance general', 'Libro Diario', 2),
('El timbrado de documentos es:', 'Un proceso fiscal de habilitación', 'Una firma digital', 'Un registro bancario', 'Una validación contable interna', 1),
('Las depreciaciones acumuladas son:', 'Pasivos', 'Ajustes de activos', 'Capital social', 'Ingresos', 2),
('Los activos intangibles incluyen:', 'Maquinarias', 'Terrenos', 'Patentes', 'Edificios', 3),
('El patrimonio neto muestra:', 'Ingresos futuros', 'Activos menos pasivos', 'Inventarios', 'Gastos', 2),
('Los anticipos a proveedores son:', 'Activos', 'Pasivos', 'Gastos', 'Reservas', 1),
('Un balance provisional es:', 'Definitivo', 'Temporal y modificable', 'De cierre anual', 'De fusión', 2),
('Las obligaciones fiscales son:', 'Impuestos y aportes', 'Reservas legales', 'Cuentas de clientes', 'Documentos por cobrar', 1),
('El capital suscripto pertenece a:', 'Pasivo', 'Patrimonio neto', 'Activos corrientes', 'Gastos financieros', 2),
('El costo de ventas se resta de:', 'Activos', 'Ventas netas', 'Reservas', 'Patrimonio', 2),
('Las cuentas por cobrar son:', 'Pasivos', 'Activos', 'Gastos', 'Reservas', 2),
('Un balance de intervención se hace en caso de:', 'Expansión', 'Quiebra o crisis', 'Fusión', 'Cambio de administración', 2),
('Los dividendos a pagar son:', 'Activos', 'Pasivos', 'Reservas', 'Gastos', 2),
('El capital de trabajo es:', 'Activos fijos', 'Activos corrientes menos pasivos corrientes', 'Ventas netas', 'Capital social', 2),
('Los intereses cobrados aparecen en:', 'Estado de Resultados', 'Balance General', 'Libro Diario', 'Libro Mayor', 1),
('La reserva de revalúo surge de:', 'Inventarios', 'Revaluación de activos', 'Capitalización de ganancias', 'Aportes patronales', 2),
('Las provisiones para incobrables ajustan:', 'Pasivos', 'Activos', 'Gastos', 'Ingresos', 2),
('El libro mayor organiza:', 'Ventas por fecha', 'Cuentas por movimientos', 'Ingresos y egresos bancarios', 'Inventarios', 2),
('Los sueldos y jornales son:', 'Activos', 'Pasivos', 'Gastos de administración', 'Ingresos', 3),
('Un balance de fusión se usa cuando:', 'Se venden activos', 'Se integran empresas', 'Se liquida la empresa', 'Se inicia actividad', 2),
('Los títulos y acciones son:', 'Activos financieros', 'Pasivos financieros', 'Reservas legales', 'Ingresos no operativos', 1),
('El impuesto a la renta aparece en:', 'Estado de Resultados', 'Balance General', 'Libro Diario', 'Libro Mayor', 1),
('Los bienes de uso incluyen:', 'Muebles y maquinarias', 'Inventarios', 'Reservas', 'Acciones', 1),
('El aporte patronal sobre salarios es:', 'Gasto', 'Ingreso', 'Pasivo', 'Reserva', 1),
('Los anticipos de clientes son:', 'Pasivos', 'Activos', 'Gastos', 'Reservas', 1);
